// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/message/message_api.proto

package messageapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncMessageRequest 同步消息请求
type SyncMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      uint32                 `protobuf:"varint,1,opt,name=selector,proto3" json:"selector,omitempty"` // 同步选择器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessageRequest) Reset() {
	*x = SyncMessageRequest{}
	mi := &file_api_message_message_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessageRequest) ProtoMessage() {}

func (x *SyncMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessageRequest.ProtoReflect.Descriptor instead.
func (*SyncMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessageRequest) GetSelector() uint32 {
	if x != nil {
		return x.Selector
	}
	return 0
}

// OperateResponse 通用操作响应（字段编号与 SDK proto 对齐）
type OperateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码（0=成功）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResponse) Reset() {
	*x = OperateResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResponse) ProtoMessage() {}

func (x *OperateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResponse.ProtoReflect.Descriptor instead.
func (*OperateResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{1}
}

func (x *OperateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SendMessageResponse 发送消息响应（字段编号与 SDK proto 对齐）
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMsgId      uint64                 `protobuf:"varint,1,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`          // 新消息 ID
	ClientMsgId   uint64                 `protobuf:"varint,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端消息 ID
	CreateTime    uint32                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`      // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *SendMessageResponse) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *SendMessageResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// UploadImageResponse 上传图片响应（字段编号与 SDK proto 对齐）
type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`              // AES 密钥
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`              // 文件 ID
	NewMsgId      uint64                 `protobuf:"varint,3,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`     // 新消息 ID
	CreateTime    uint32                 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	FileSize      uint32                 `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`       // 文件大小
	FileMd5       string                 `protobuf:"bytes,6,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`           // 文件 MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{3}
}

func (x *UploadImageResponse) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadImageResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadImageResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadImageResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UploadImageResponse) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadImageResponse) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// UploadVideoResponse 上传视频响应（字段编号与 SDK proto 对齐）
type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // AES 密钥
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // 文件 ID
	FileSize      uint32                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // 文件大小
	ThumbSize     uint32                 `protobuf:"varint,4,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size,omitempty"` // 缩略图大小
	FileMd5       string                 `protobuf:"bytes,5,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`        // 文件 MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{4}
}

func (x *UploadVideoResponse) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadVideoResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadVideoResponse) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadVideoResponse) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *UploadVideoResponse) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// UploadVoiceResponse 上传语音响应（字段编号与 SDK proto 对齐）
type UploadVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`              // AES 密钥
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`              // 文件 ID
	NewMsgId      uint64                 `protobuf:"varint,3,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`     // 新消息 ID
	CreateTime    uint32                 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVoiceResponse) Reset() {
	*x = UploadVoiceResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVoiceResponse) ProtoMessage() {}

func (x *UploadVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVoiceResponse.ProtoReflect.Descriptor instead.
func (*UploadVoiceResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{5}
}

func (x *UploadVoiceResponse) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadVoiceResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadVoiceResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadVoiceResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// UploadEmojiResponse 上传表情响应（字段编号与 SDK proto 对齐）
type UploadEmojiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Md5           string                 `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`                                  // 表情 MD5
	NewMsgId      uint64                 `protobuf:"varint,2,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`     // 新消息 ID
	CreateTime    uint32                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEmojiResponse) Reset() {
	*x = UploadEmojiResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEmojiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEmojiResponse) ProtoMessage() {}

func (x *UploadEmojiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEmojiResponse.ProtoReflect.Descriptor instead.
func (*UploadEmojiResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{6}
}

func (x *UploadEmojiResponse) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *UploadEmojiResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadEmojiResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SendAppMessageResponse 发送应用消息响应（字段编号与 SDK proto 对齐）
type SendAppMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMsgId      uint64                 `protobuf:"varint,1,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`          // 新消息 ID
	ClientMsgId   uint64                 `protobuf:"varint,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端消息 ID
	CreateTime    uint32                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`      // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAppMessageResponse) Reset() {
	*x = SendAppMessageResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAppMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAppMessageResponse) ProtoMessage() {}

func (x *SendAppMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAppMessageResponse.ProtoReflect.Descriptor instead.
func (*SendAppMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{7}
}

func (x *SendAppMessageResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *SendAppMessageResponse) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *SendAppMessageResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// RevokeMessageResponse 撤回消息响应（字段编号与 SDK proto 对齐）
type RevokeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMessageResponse) Reset() {
	*x = RevokeMessageResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageResponse) ProtoMessage() {}

func (x *RevokeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageResponse.ProtoReflect.Descriptor instead.
func (*RevokeMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeMessageResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RevokeMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DownloadImageResponse 下载图片响应（字段编号与 SDK proto 对齐）
type DownloadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 图片数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageResponse) Reset() {
	*x = DownloadImageResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageResponse) ProtoMessage() {}

func (x *DownloadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageResponse.ProtoReflect.Descriptor instead.
func (*DownloadImageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVideoResponse 下载视频响应（字段编号与 SDK proto 对齐）
type DownloadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 视频数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoResponse) Reset() {
	*x = DownloadVideoResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoResponse) ProtoMessage() {}

func (x *DownloadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoResponse.ProtoReflect.Descriptor instead.
func (*DownloadVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadVideoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVoiceResponse 下载语音响应（字段编号与 SDK proto 对齐）
type DownloadVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 语音数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVoiceResponse) Reset() {
	*x = DownloadVoiceResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVoiceResponse) ProtoMessage() {}

func (x *DownloadVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVoiceResponse.ProtoReflect.Descriptor instead.
func (*DownloadVoiceResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadVoiceResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadFileResponse 下载文件响应（字段编号与 SDK proto 对齐）
type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 文件数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_api_message_message_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_message_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_message_message_api_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_message_message_api_proto protoreflect.FileDescriptor

const file_api_message_message_api_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/message/message_api.proto\x12\vmessage.api\"0\n" +
	"\x12SyncMessageRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\rR\bselector\"?\n" +
	"\x0fOperateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x13SendMessageResponse\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x01 \x01(\x04R\bnewMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\x04R\vclientMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\rR\n" +
	"createTime\"\xbe\x01\n" +
	"\x13UploadImageResponse\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x03 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\rR\n" +
	"createTime\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\rR\bfileSize\x12\x19\n" +
	"\bfile_md5\x18\x06 \x01(\tR\afileMd5\"\x9e\x01\n" +
	"\x13UploadVideoResponse\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\rR\bfileSize\x12\x1d\n" +
	"\n" +
	"thumb_size\x18\x04 \x01(\rR\tthumbSize\x12\x19\n" +
	"\bfile_md5\x18\x05 \x01(\tR\afileMd5\"\x86\x01\n" +
	"\x13UploadVoiceResponse\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x03 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\rR\n" +
	"createTime\"f\n" +
	"\x13UploadEmojiResponse\x12\x10\n" +
	"\x03md5\x18\x01 \x01(\tR\x03md5\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x02 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\rR\n" +
	"createTime\"{\n" +
	"\x16SendAppMessageResponse\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x01 \x01(\x04R\bnewMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\x04R\vclientMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\rR\n" +
	"createTime\"E\n" +
	"\x15RevokeMessageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x15DownloadImageResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"+\n" +
	"\x15DownloadVideoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"+\n" +
	"\x15DownloadVoiceResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"*\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB7Z5github.com/sbgayhub/golem/host/api/message;messageapib\x06proto3"

var (
	file_api_message_message_api_proto_rawDescOnce sync.Once
	file_api_message_message_api_proto_rawDescData []byte
)

func file_api_message_message_api_proto_rawDescGZIP() []byte {
	file_api_message_message_api_proto_rawDescOnce.Do(func() {
		file_api_message_message_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_message_message_api_proto_rawDesc), len(file_api_message_message_api_proto_rawDesc)))
	})
	return file_api_message_message_api_proto_rawDescData
}

var file_api_message_message_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_message_message_api_proto_goTypes = []any{
	(*SyncMessageRequest)(nil),     // 0: message.api.SyncMessageRequest
	(*OperateResponse)(nil),        // 1: message.api.OperateResponse
	(*SendMessageResponse)(nil),    // 2: message.api.SendMessageResponse
	(*UploadImageResponse)(nil),    // 3: message.api.UploadImageResponse
	(*UploadVideoResponse)(nil),    // 4: message.api.UploadVideoResponse
	(*UploadVoiceResponse)(nil),    // 5: message.api.UploadVoiceResponse
	(*UploadEmojiResponse)(nil),    // 6: message.api.UploadEmojiResponse
	(*SendAppMessageResponse)(nil), // 7: message.api.SendAppMessageResponse
	(*RevokeMessageResponse)(nil),  // 8: message.api.RevokeMessageResponse
	(*DownloadImageResponse)(nil),  // 9: message.api.DownloadImageResponse
	(*DownloadVideoResponse)(nil),  // 10: message.api.DownloadVideoResponse
	(*DownloadVoiceResponse)(nil),  // 11: message.api.DownloadVoiceResponse
	(*DownloadFileResponse)(nil),   // 12: message.api.DownloadFileResponse
}
var file_api_message_message_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_message_message_api_proto_init() }
func file_api_message_message_api_proto_init() {
	if File_api_message_message_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_message_message_api_proto_rawDesc), len(file_api_message_message_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_message_message_api_proto_goTypes,
		DependencyIndexes: file_api_message_message_api_proto_depIdxs,
		MessageInfos:      file_api_message_message_api_proto_msgTypes,
	}.Build()
	File_api_message_message_api_proto = out.File
	file_api_message_message_api_proto_goTypes = nil
	file_api_message_message_api_proto_depIdxs = nil
}
