// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: message/message_api.proto

package messageapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncMessageRequest 同步消息请求
type SyncMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      uint32                 `protobuf:"varint,1,opt,name=selector,proto3" json:"selector,omitempty"` // 同步选择器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessageRequest) Reset() {
	*x = SyncMessageRequest{}
	mi := &file_message_message_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessageRequest) ProtoMessage() {}

func (x *SyncMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessageRequest.ProtoReflect.Descriptor instead.
func (*SyncMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessageRequest) GetSelector() uint32 {
	if x != nil {
		return x.Selector
	}
	return 0
}

// SyncMessageResponse 同步消息响应（字段编号与 SDK proto 对齐）
type SyncMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessageResponse) Reset() {
	*x = SyncMessageResponse{}
	mi := &file_message_message_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessageResponse) ProtoMessage() {}

func (x *SyncMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessageResponse.ProtoReflect.Descriptor instead.
func (*SyncMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{1}
}

func (x *SyncMessageResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// OperateResponse 通用操作响应（字段编号与 SDK proto 对齐）
type OperateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码（0=成功）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResponse) Reset() {
	*x = OperateResponse{}
	mi := &file_message_message_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResponse) ProtoMessage() {}

func (x *OperateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResponse.ProtoReflect.Descriptor instead.
func (*OperateResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{2}
}

func (x *OperateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SendTextRequest 发送文本消息请求
type SendTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`   // 消息内容
	Remind        string                 `protobuf:"bytes,3,opt,name=remind,proto3" json:"remind,omitempty"`     // 被@的用户名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_message_message_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{3}
}

func (x *SendTextRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendTextRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendTextRequest) GetRemind() string {
	if x != nil {
		return x.Remind
	}
	return ""
}

// SendMessageResponse 发送消息响应（字段编号与 SDK proto 对齐）
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMsgId      uint64                 `protobuf:"varint,1,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`          // 新消息 ID
	ClientMsgId   uint64                 `protobuf:"varint,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端消息 ID
	CreateTime    uint32                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`      // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_message_message_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *SendMessageResponse) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *SendMessageResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SendImageRequest 发送图片消息请求
type SendImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // 图片数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImageRequest) Reset() {
	*x = SendImageRequest{}
	mi := &file_message_message_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImageRequest) ProtoMessage() {}

func (x *SendImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImageRequest.ProtoReflect.Descriptor instead.
func (*SendImageRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{5}
}

func (x *SendImageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadImageResponse 上传图片响应（字段编号与 SDK proto 对齐）
type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`              // AES 密钥
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`              // 文件 ID
	NewMsgId      uint64                 `protobuf:"varint,3,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`     // 新消息 ID
	CreateTime    uint32                 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	FileSize      uint32                 `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`       // 文件大小
	FileMd5       string                 `protobuf:"bytes,6,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`           // 文件 MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_message_message_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{6}
}

func (x *UploadImageResponse) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadImageResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadImageResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadImageResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UploadImageResponse) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadImageResponse) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// SendVideoRequest 发送视频消息请求
type SendVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`  // 接收者
	Thumb         []byte                 `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"`        // 缩略图数据
	Video         []byte                 `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`        // 视频数据
	Duration      uint32                 `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // 视频时长（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVideoRequest) Reset() {
	*x = SendVideoRequest{}
	mi := &file_message_message_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVideoRequest) ProtoMessage() {}

func (x *SendVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVideoRequest.ProtoReflect.Descriptor instead.
func (*SendVideoRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{7}
}

func (x *SendVideoRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendVideoRequest) GetThumb() []byte {
	if x != nil {
		return x.Thumb
	}
	return nil
}

func (x *SendVideoRequest) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *SendVideoRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// UploadVideoResponse 上传视频响应（字段编号与 SDK proto 对齐）
type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // AES 密钥
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // 文件 ID
	FileSize      uint32                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // 文件大小
	ThumbSize     uint32                 `protobuf:"varint,4,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size,omitempty"` // 缩略图大小
	FileMd5       string                 `protobuf:"bytes,5,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`        // 文件 MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_message_message_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{8}
}

func (x *UploadVideoResponse) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadVideoResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadVideoResponse) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadVideoResponse) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *UploadVideoResponse) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// SendVoiceRequest 发送语音消息请求
type SendVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`  // 接收者
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`          // 语音数据
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"` // 时长（秒）
	Format        int32                  `protobuf:"varint,4,opt,name=format,proto3" json:"format,omitempty"`     // 格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVoiceRequest) Reset() {
	*x = SendVoiceRequest{}
	mi := &file_message_message_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVoiceRequest) ProtoMessage() {}

func (x *SendVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVoiceRequest.ProtoReflect.Descriptor instead.
func (*SendVoiceRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{9}
}

func (x *SendVoiceRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendVoiceRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendVoiceRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SendVoiceRequest) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

// UploadVoiceResponse 上传语音响应（字段编号与 SDK proto 对齐）
type UploadVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`              // AES 密钥
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`              // 文件 ID
	NewMsgId      uint64                 `protobuf:"varint,3,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`     // 新消息 ID
	CreateTime    uint32                 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVoiceResponse) Reset() {
	*x = UploadVoiceResponse{}
	mi := &file_message_message_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVoiceResponse) ProtoMessage() {}

func (x *UploadVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVoiceResponse.ProtoReflect.Descriptor instead.
func (*UploadVoiceResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{10}
}

func (x *UploadVoiceResponse) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadVoiceResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadVoiceResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadVoiceResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SendEmojiRequest 发送表情消息请求
type SendEmojiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Md5           string                 `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`           // 表情 MD5
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`         // 表情数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmojiRequest) Reset() {
	*x = SendEmojiRequest{}
	mi := &file_message_message_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmojiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmojiRequest) ProtoMessage() {}

func (x *SendEmojiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmojiRequest.ProtoReflect.Descriptor instead.
func (*SendEmojiRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{11}
}

func (x *SendEmojiRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendEmojiRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *SendEmojiRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadEmojiResponse 上传表情响应（字段编号与 SDK proto 对齐）
type UploadEmojiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Md5           string                 `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`                                  // 表情 MD5
	NewMsgId      uint64                 `protobuf:"varint,2,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`     // 新消息 ID
	CreateTime    uint32                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEmojiResponse) Reset() {
	*x = UploadEmojiResponse{}
	mi := &file_message_message_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEmojiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEmojiResponse) ProtoMessage() {}

func (x *UploadEmojiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEmojiResponse.ProtoReflect.Descriptor instead.
func (*UploadEmojiResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{12}
}

func (x *UploadEmojiResponse) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *UploadEmojiResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadEmojiResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SendAppRequest 发送应用消息请求
type SendAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Xml           string                 `protobuf:"bytes,2,opt,name=xml,proto3" json:"xml,omitempty"`           // XML 内容
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`        // 消息类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAppRequest) Reset() {
	*x = SendAppRequest{}
	mi := &file_message_message_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAppRequest) ProtoMessage() {}

func (x *SendAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAppRequest.ProtoReflect.Descriptor instead.
func (*SendAppRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{13}
}

func (x *SendAppRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendAppRequest) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

func (x *SendAppRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// SendAppMessageResponse 发送应用消息响应（字段编号与 SDK proto 对齐）
type SendAppMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMsgId      uint64                 `protobuf:"varint,1,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`          // 新消息 ID
	ClientMsgId   uint64                 `protobuf:"varint,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端消息 ID
	CreateTime    uint32                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`      // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAppMessageResponse) Reset() {
	*x = SendAppMessageResponse{}
	mi := &file_message_message_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAppMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAppMessageResponse) ProtoMessage() {}

func (x *SendAppMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAppMessageResponse.ProtoReflect.Descriptor instead.
func (*SendAppMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{14}
}

func (x *SendAppMessageResponse) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *SendAppMessageResponse) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *SendAppMessageResponse) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SendLinkRequest 发送链接消息请求
type SendLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                 // 接收者
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                       // 标题
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`           // 描述
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                           // 链接 URL
	ThumbUrl      string                 `protobuf:"bytes,5,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"` // 缩略图 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLinkRequest) Reset() {
	*x = SendLinkRequest{}
	mi := &file_message_message_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLinkRequest) ProtoMessage() {}

func (x *SendLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLinkRequest.ProtoReflect.Descriptor instead.
func (*SendLinkRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{15}
}

func (x *SendLinkRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendLinkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SendLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SendLinkRequest) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

// SendCardRequest 发送名片消息请求
type SendCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                             // 接收者
	CardUsername  string                 `protobuf:"bytes,2,opt,name=card_username,json=cardUsername,proto3" json:"card_username,omitempty"` // 名片用户名
	CardNickname  string                 `protobuf:"bytes,3,opt,name=card_nickname,json=cardNickname,proto3" json:"card_nickname,omitempty"` // 名片昵称
	CardAlias     string                 `protobuf:"bytes,4,opt,name=card_alias,json=cardAlias,proto3" json:"card_alias,omitempty"`          // 名片微信号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCardRequest) Reset() {
	*x = SendCardRequest{}
	mi := &file_message_message_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardRequest) ProtoMessage() {}

func (x *SendCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardRequest.ProtoReflect.Descriptor instead.
func (*SendCardRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{16}
}

func (x *SendCardRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendCardRequest) GetCardUsername() string {
	if x != nil {
		return x.CardUsername
	}
	return ""
}

func (x *SendCardRequest) GetCardNickname() string {
	if x != nil {
		return x.CardNickname
	}
	return ""
}

func (x *SendCardRequest) GetCardAlias() string {
	if x != nil {
		return x.CardAlias
	}
	return ""
}

// SendPositionRequest 发送位置消息请求
type SendPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`              // 接收者
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                    // 位置标签
	PoiName       string                 `protobuf:"bytes,3,opt,name=poi_name,json=poiName,proto3" json:"poi_name,omitempty"` // POI 名称
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`          // 经度
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`            // 纬度
	Scale         float64                `protobuf:"fixed64,6,opt,name=scale,proto3" json:"scale,omitempty"`                  // 缩放比例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPositionRequest) Reset() {
	*x = SendPositionRequest{}
	mi := &file_message_message_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPositionRequest) ProtoMessage() {}

func (x *SendPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPositionRequest.ProtoReflect.Descriptor instead.
func (*SendPositionRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{17}
}

func (x *SendPositionRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendPositionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SendPositionRequest) GetPoiName() string {
	if x != nil {
		return x.PoiName
	}
	return ""
}

func (x *SendPositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SendPositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SendPositionRequest) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// ForwardImageRequest 转发 CDN 图片请求
type ForwardImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // 图片数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardImageRequest) Reset() {
	*x = ForwardImageRequest{}
	mi := &file_message_message_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardImageRequest) ProtoMessage() {}

func (x *ForwardImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardImageRequest.ProtoReflect.Descriptor instead.
func (*ForwardImageRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{18}
}

func (x *ForwardImageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ForwardImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ForwardVideoRequest 转发 CDN 视频请求
type ForwardVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // 视频数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardVideoRequest) Reset() {
	*x = ForwardVideoRequest{}
	mi := &file_message_message_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardVideoRequest) ProtoMessage() {}

func (x *ForwardVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardVideoRequest.ProtoReflect.Descriptor instead.
func (*ForwardVideoRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{19}
}

func (x *ForwardVideoRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ForwardVideoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ForwardFileRequest 转发文件请求
type ForwardFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者
	Xml           string                 `protobuf:"bytes,2,opt,name=xml,proto3" json:"xml,omitempty"`           // 文件 XML
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardFileRequest) Reset() {
	*x = ForwardFileRequest{}
	mi := &file_message_message_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardFileRequest) ProtoMessage() {}

func (x *ForwardFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardFileRequest.ProtoReflect.Descriptor instead.
func (*ForwardFileRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{20}
}

func (x *ForwardFileRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ForwardFileRequest) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

// RevokeMessageRequest 撤回消息请求
type RevokeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                             // 接收者/会话
	NewMsgId      uint64                 `protobuf:"varint,2,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`          // 新消息 ID
	ClientMsgId   uint64                 `protobuf:"varint,3,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端消息 ID
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMessageRequest) Reset() {
	*x = RevokeMessageRequest{}
	mi := &file_message_message_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageRequest) ProtoMessage() {}

func (x *RevokeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageRequest.ProtoReflect.Descriptor instead.
func (*RevokeMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{21}
}

func (x *RevokeMessageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *RevokeMessageRequest) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *RevokeMessageRequest) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *RevokeMessageRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// RevokeMessageResponse 撤回消息响应（字段编号与 SDK proto 对齐）
type RevokeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMessageResponse) Reset() {
	*x = RevokeMessageResponse{}
	mi := &file_message_message_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageResponse) ProtoMessage() {}

func (x *RevokeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageResponse.ProtoReflect.Descriptor instead.
func (*RevokeMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{22}
}

func (x *RevokeMessageResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RevokeMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DownloadImgRequest 下载图片请求
type DownloadImgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                     // 发送者
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // 文件 ID
	AesKey        string                 `protobuf:"bytes,3,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // AES 密钥
	TotalSize     uint32                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // 总大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImgRequest) Reset() {
	*x = DownloadImgRequest{}
	mi := &file_message_message_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImgRequest) ProtoMessage() {}

func (x *DownloadImgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImgRequest.ProtoReflect.Descriptor instead.
func (*DownloadImgRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{23}
}

func (x *DownloadImgRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *DownloadImgRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadImgRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *DownloadImgRequest) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// DownloadImageResponse 下载图片响应（字段编号与 SDK proto 对齐）
type DownloadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 图片数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageResponse) Reset() {
	*x = DownloadImageResponse{}
	mi := &file_message_message_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageResponse) ProtoMessage() {}

func (x *DownloadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageResponse.ProtoReflect.Descriptor instead.
func (*DownloadImageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{24}
}

func (x *DownloadImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVideoRequest 下载视频请求
type DownloadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                     // 发送者
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // 文件 ID
	AesKey        string                 `protobuf:"bytes,3,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // AES 密钥
	TotalSize     uint32                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // 总大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoRequest) Reset() {
	*x = DownloadVideoRequest{}
	mi := &file_message_message_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoRequest) ProtoMessage() {}

func (x *DownloadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoRequest.ProtoReflect.Descriptor instead.
func (*DownloadVideoRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{25}
}

func (x *DownloadVideoRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *DownloadVideoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadVideoRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *DownloadVideoRequest) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// DownloadVideoResponse 下载视频响应（字段编号与 SDK proto 对齐）
type DownloadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 视频数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoResponse) Reset() {
	*x = DownloadVideoResponse{}
	mi := &file_message_message_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoResponse) ProtoMessage() {}

func (x *DownloadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoResponse.ProtoReflect.Descriptor instead.
func (*DownloadVideoResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{26}
}

func (x *DownloadVideoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVoiceRequest 下载语音请求
type DownloadVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                           // 发送者
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                 // 文件 ID
	AesKey        string                 `protobuf:"bytes,3,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`                 // AES 密钥
	TotalSize     uint32                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`       // 总大小
	VoiceLength   uint32                 `protobuf:"varint,5,opt,name=voice_length,json=voiceLength,proto3" json:"voice_length,omitempty"` // 语音长度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVoiceRequest) Reset() {
	*x = DownloadVoiceRequest{}
	mi := &file_message_message_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVoiceRequest) ProtoMessage() {}

func (x *DownloadVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVoiceRequest.ProtoReflect.Descriptor instead.
func (*DownloadVoiceRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{27}
}

func (x *DownloadVoiceRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *DownloadVoiceRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadVoiceRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *DownloadVoiceRequest) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *DownloadVoiceRequest) GetVoiceLength() uint32 {
	if x != nil {
		return x.VoiceLength
	}
	return 0
}

// DownloadVoiceResponse 下载语音响应（字段编号与 SDK proto 对齐）
type DownloadVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 语音数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVoiceResponse) Reset() {
	*x = DownloadVoiceResponse{}
	mi := &file_message_message_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVoiceResponse) ProtoMessage() {}

func (x *DownloadVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVoiceResponse.ProtoReflect.Descriptor instead.
func (*DownloadVoiceResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{28}
}

func (x *DownloadVoiceResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadFileRequest 下载文件附件请求
type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                     // 发送者
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // 文件 ID
	AesKey        string                 `protobuf:"bytes,3,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // AES 密钥
	TotalSize     uint32                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // 总大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_message_message_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{29}
}

func (x *DownloadFileRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *DownloadFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadFileRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *DownloadFileRequest) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// DownloadFileResponse 下载文件响应（字段编号与 SDK proto 对齐）
type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 文件数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_message_message_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_message_message_api_proto_rawDescGZIP(), []int{30}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_message_message_api_proto protoreflect.FileDescriptor

const file_message_message_api_proto_rawDesc = "" +
	"\n" +
	"\x19message/message_api.proto\x12\vmessage.api\"0\n" +
	"\x12SyncMessageRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\rR\bselector\"C\n" +
	"\x13SyncMessageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x0fOperateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x0fSendTextRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06remind\x18\x03 \x01(\tR\x06remind\"x\n" +
	"\x13SendMessageResponse\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x01 \x01(\x04R\bnewMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\x04R\vclientMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\rR\n" +
	"createTime\"B\n" +
	"\x10SendImageRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xbe\x01\n" +
	"\x13UploadImageResponse\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x03 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\rR\n" +
	"createTime\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\rR\bfileSize\x12\x19\n" +
	"\bfile_md5\x18\x06 \x01(\tR\afileMd5\"v\n" +
	"\x10SendVideoRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x14\n" +
	"\x05thumb\x18\x02 \x01(\fR\x05thumb\x12\x14\n" +
	"\x05video\x18\x03 \x01(\fR\x05video\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\rR\bduration\"\x9e\x01\n" +
	"\x13UploadVideoResponse\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\rR\bfileSize\x12\x1d\n" +
	"\n" +
	"thumb_size\x18\x04 \x01(\rR\tthumbSize\x12\x19\n" +
	"\bfile_md5\x18\x05 \x01(\tR\afileMd5\"v\n" +
	"\x10SendVoiceRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x16\n" +
	"\x06format\x18\x04 \x01(\x05R\x06format\"\x86\x01\n" +
	"\x13UploadVoiceResponse\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x03 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\rR\n" +
	"createTime\"T\n" +
	"\x10SendEmojiRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x10\n" +
	"\x03md5\x18\x02 \x01(\tR\x03md5\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"f\n" +
	"\x13UploadEmojiResponse\x12\x10\n" +
	"\x03md5\x18\x01 \x01(\tR\x03md5\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x02 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\rR\n" +
	"createTime\"R\n" +
	"\x0eSendAppRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x10\n" +
	"\x03xml\x18\x02 \x01(\tR\x03xml\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"{\n" +
	"\x16SendAppMessageResponse\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x01 \x01(\x04R\bnewMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\x04R\vclientMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\rR\n" +
	"createTime\"\x94\x01\n" +
	"\x0fSendLinkRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\tthumb_url\x18\x05 \x01(\tR\bthumbUrl\"\x96\x01\n" +
	"\x0fSendCardRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12#\n" +
	"\rcard_username\x18\x02 \x01(\tR\fcardUsername\x12#\n" +
	"\rcard_nickname\x18\x03 \x01(\tR\fcardNickname\x12\x1d\n" +
	"\n" +
	"card_alias\x18\x04 \x01(\tR\tcardAlias\"\xb2\x01\n" +
	"\x13SendPositionRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x19\n" +
	"\bpoi_name\x18\x03 \x01(\tR\apoiName\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x14\n" +
	"\x05scale\x18\x06 \x01(\x01R\x05scale\"E\n" +
	"\x13ForwardImageRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"E\n" +
	"\x13ForwardVideoRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\x12ForwardFileRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x10\n" +
	"\x03xml\x18\x02 \x01(\tR\x03xml\"\x92\x01\n" +
	"\x14RevokeMessageRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x02 \x01(\x04R\bnewMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x03 \x01(\x04R\vclientMsgId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"E\n" +
	"\x15RevokeMessageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\x12DownloadImgRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x03 \x01(\tR\x06aesKey\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\rR\ttotalSize\"+\n" +
	"\x15DownloadImageResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x83\x01\n" +
	"\x14DownloadVideoRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x03 \x01(\tR\x06aesKey\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\rR\ttotalSize\"+\n" +
	"\x15DownloadVideoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa6\x01\n" +
	"\x14DownloadVoiceRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x03 \x01(\tR\x06aesKey\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\rR\ttotalSize\x12!\n" +
	"\fvoice_length\x18\x05 \x01(\rR\vvoiceLength\"+\n" +
	"\x15DownloadVoiceResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x82\x01\n" +
	"\x13DownloadFileRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x03 \x01(\tR\x06aesKey\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\rR\ttotalSize\"*\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB7Z5github.com/sbgayhub/golem/host/api/message;messageapib\x06proto3"

var (
	file_message_message_api_proto_rawDescOnce sync.Once
	file_message_message_api_proto_rawDescData []byte
)

func file_message_message_api_proto_rawDescGZIP() []byte {
	file_message_message_api_proto_rawDescOnce.Do(func() {
		file_message_message_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_api_proto_rawDesc), len(file_message_message_api_proto_rawDesc)))
	})
	return file_message_message_api_proto_rawDescData
}

var file_message_message_api_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_message_message_api_proto_goTypes = []any{
	(*SyncMessageRequest)(nil),     // 0: message.api.SyncMessageRequest
	(*SyncMessageResponse)(nil),    // 1: message.api.SyncMessageResponse
	(*OperateResponse)(nil),        // 2: message.api.OperateResponse
	(*SendTextRequest)(nil),        // 3: message.api.SendTextRequest
	(*SendMessageResponse)(nil),    // 4: message.api.SendMessageResponse
	(*SendImageRequest)(nil),       // 5: message.api.SendImageRequest
	(*UploadImageResponse)(nil),    // 6: message.api.UploadImageResponse
	(*SendVideoRequest)(nil),       // 7: message.api.SendVideoRequest
	(*UploadVideoResponse)(nil),    // 8: message.api.UploadVideoResponse
	(*SendVoiceRequest)(nil),       // 9: message.api.SendVoiceRequest
	(*UploadVoiceResponse)(nil),    // 10: message.api.UploadVoiceResponse
	(*SendEmojiRequest)(nil),       // 11: message.api.SendEmojiRequest
	(*UploadEmojiResponse)(nil),    // 12: message.api.UploadEmojiResponse
	(*SendAppRequest)(nil),         // 13: message.api.SendAppRequest
	(*SendAppMessageResponse)(nil), // 14: message.api.SendAppMessageResponse
	(*SendLinkRequest)(nil),        // 15: message.api.SendLinkRequest
	(*SendCardRequest)(nil),        // 16: message.api.SendCardRequest
	(*SendPositionRequest)(nil),    // 17: message.api.SendPositionRequest
	(*ForwardImageRequest)(nil),    // 18: message.api.ForwardImageRequest
	(*ForwardVideoRequest)(nil),    // 19: message.api.ForwardVideoRequest
	(*ForwardFileRequest)(nil),     // 20: message.api.ForwardFileRequest
	(*RevokeMessageRequest)(nil),   // 21: message.api.RevokeMessageRequest
	(*RevokeMessageResponse)(nil),  // 22: message.api.RevokeMessageResponse
	(*DownloadImgRequest)(nil),     // 23: message.api.DownloadImgRequest
	(*DownloadImageResponse)(nil),  // 24: message.api.DownloadImageResponse
	(*DownloadVideoRequest)(nil),   // 25: message.api.DownloadVideoRequest
	(*DownloadVideoResponse)(nil),  // 26: message.api.DownloadVideoResponse
	(*DownloadVoiceRequest)(nil),   // 27: message.api.DownloadVoiceRequest
	(*DownloadVoiceResponse)(nil),  // 28: message.api.DownloadVoiceResponse
	(*DownloadFileRequest)(nil),    // 29: message.api.DownloadFileRequest
	(*DownloadFileResponse)(nil),   // 30: message.api.DownloadFileResponse
}
var file_message_message_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_message_api_proto_init() }
func file_message_message_api_proto_init() {
	if File_message_message_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_api_proto_rawDesc), len(file_message_message_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_message_api_proto_goTypes,
		DependencyIndexes: file_message_message_api_proto_depIdxs,
		MessageInfos:      file_message_message_api_proto_msgTypes,
	}.Build()
	File_message_message_api_proto = out.File
	file_message_message_api_proto_goTypes = nil
	file_message_message_api_proto_depIdxs = nil
}
