// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: cdn/cdn.proto

package cdn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DownloadType CDN下载类型
type DownloadType int32

const (
	DownloadType_DOWNLOAD_TYPE_UNSPECIFIED DownloadType = 0 // 未指定
	DownloadType_DOWNLOAD_TYPE_IMAGE       DownloadType = 1 // 下载图片
	DownloadType_DOWNLOAD_TYPE_VIDEO       DownloadType = 2 // 下载视频
	DownloadType_DOWNLOAD_TYPE_VIDEO_COVER DownloadType = 3 // 下载视频封面
	DownloadType_DOWNLOAD_TYPE_SNS_VIDEO   DownloadType = 4 // 下载朋友圈视频
)

// Enum value maps for DownloadType.
var (
	DownloadType_name = map[int32]string{
		0: "DOWNLOAD_TYPE_UNSPECIFIED",
		1: "DOWNLOAD_TYPE_IMAGE",
		2: "DOWNLOAD_TYPE_VIDEO",
		3: "DOWNLOAD_TYPE_VIDEO_COVER",
		4: "DOWNLOAD_TYPE_SNS_VIDEO",
	}
	DownloadType_value = map[string]int32{
		"DOWNLOAD_TYPE_UNSPECIFIED": 0,
		"DOWNLOAD_TYPE_IMAGE":       1,
		"DOWNLOAD_TYPE_VIDEO":       2,
		"DOWNLOAD_TYPE_VIDEO_COVER": 3,
		"DOWNLOAD_TYPE_SNS_VIDEO":   4,
	}
)

func (x DownloadType) Enum() *DownloadType {
	p := new(DownloadType)
	*p = x
	return p
}

func (x DownloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_cdn_cdn_proto_enumTypes[0].Descriptor()
}

func (DownloadType) Type() protoreflect.EnumType {
	return &file_cdn_cdn_proto_enumTypes[0]
}

func (x DownloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadType.Descriptor instead.
func (DownloadType) EnumDescriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{0}
}

// UploadImageResult 聊天图片 CDN 上传结果
type UploadImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`                  // 图片加密 AES 密钥（hex编码）
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                  // CDN 文件ID
	NewMsgId      uint64                 `protobuf:"varint,3,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`         // 新消息ID
	CreateTime    uint32                 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`     // 创建时间
	FileSize      uint32                 `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`           // 文件大小
	FileMd5       string                 `protobuf:"bytes,6,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`               // 文件MD5
	FileWidth     uint32                 `protobuf:"varint,7,opt,name=file_width,json=fileWidth,proto3" json:"file_width,omitempty"`        // 图片宽度
	FileHeight    uint32                 `protobuf:"varint,8,opt,name=file_height,json=fileHeight,proto3" json:"file_height,omitempty"`     // 图片高度
	ThumbSize     uint32                 `protobuf:"varint,9,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size,omitempty"`        // 缩略图大小
	ThumbMd5      string                 `protobuf:"bytes,10,opt,name=thumb_md5,json=thumbMd5,proto3" json:"thumb_md5,omitempty"`           // 缩略图MD5
	ThumbWidth    uint32                 `protobuf:"varint,11,opt,name=thumb_width,json=thumbWidth,proto3" json:"thumb_width,omitempty"`    // 缩略图宽度
	ThumbHeight   uint32                 `protobuf:"varint,12,opt,name=thumb_height,json=thumbHeight,proto3" json:"thumb_height,omitempty"` // 缩略图高度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResult) Reset() {
	*x = UploadImageResult{}
	mi := &file_cdn_cdn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResult) ProtoMessage() {}

func (x *UploadImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResult.ProtoReflect.Descriptor instead.
func (*UploadImageResult) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageResult) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadImageResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadImageResult) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadImageResult) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UploadImageResult) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadImageResult) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *UploadImageResult) GetFileWidth() uint32 {
	if x != nil {
		return x.FileWidth
	}
	return 0
}

func (x *UploadImageResult) GetFileHeight() uint32 {
	if x != nil {
		return x.FileHeight
	}
	return 0
}

func (x *UploadImageResult) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *UploadImageResult) GetThumbMd5() string {
	if x != nil {
		return x.ThumbMd5
	}
	return ""
}

func (x *UploadImageResult) GetThumbWidth() uint32 {
	if x != nil {
		return x.ThumbWidth
	}
	return 0
}

func (x *UploadImageResult) GetThumbHeight() uint32 {
	if x != nil {
		return x.ThumbHeight
	}
	return 0
}

// UploadSnsImageResult 朋友圈图片 CDN 上传结果
type UploadSnsImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`              // CDN 文件URL
	ThumbUrl      string                 `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`           // CDN 缩略图URL
	FileKey       string                 `protobuf:"bytes,3,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`              // 文件Key
	FileMd5       string                 `protobuf:"bytes,4,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`              // 文件MD5
	ImageWidth    uint32                 `protobuf:"varint,5,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`    // 图片宽度
	ImageHeight   uint32                 `protobuf:"varint,6,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"` // 图片高度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnsImageResult) Reset() {
	*x = UploadSnsImageResult{}
	mi := &file_cdn_cdn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnsImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnsImageResult) ProtoMessage() {}

func (x *UploadSnsImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnsImageResult.ProtoReflect.Descriptor instead.
func (*UploadSnsImageResult) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSnsImageResult) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadSnsImageResult) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *UploadSnsImageResult) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *UploadSnsImageResult) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *UploadSnsImageResult) GetImageWidth() uint32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *UploadSnsImageResult) GetImageHeight() uint32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

// UploadVideoResult 聊天视频 CDN 上传结果
type UploadVideoResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // 视频加密 AES 密钥（hex编码）
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // CDN 文件ID
	FileSize      uint32                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // 视频文件大小
	ThumbSize     uint32                 `protobuf:"varint,4,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size,omitempty"` // 缩略图大小
	FileMd5       string                 `protobuf:"bytes,5,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`        // 视频MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResult) Reset() {
	*x = UploadVideoResult{}
	mi := &file_cdn_cdn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResult) ProtoMessage() {}

func (x *UploadVideoResult) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResult.ProtoReflect.Descriptor instead.
func (*UploadVideoResult) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoResult) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadVideoResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadVideoResult) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadVideoResult) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *UploadVideoResult) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// UploadSnsVideoResult 朋友圈视频 CDN 上传结果
type UploadSnsVideoResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`    // CDN 视频URL
	ThumbUrl      string                 `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"` // CDN 缩略图URL
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`       // 文件ID
	FileKey       string                 `protobuf:"bytes,4,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`    // 文件Key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnsVideoResult) Reset() {
	*x = UploadSnsVideoResult{}
	mi := &file_cdn_cdn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnsVideoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnsVideoResult) ProtoMessage() {}

func (x *UploadSnsVideoResult) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnsVideoResult.ProtoReflect.Descriptor instead.
func (*UploadSnsVideoResult) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{3}
}

func (x *UploadSnsVideoResult) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadSnsVideoResult) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *UploadSnsVideoResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadSnsVideoResult) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

// DnsResponse CDN DNS 响应
type DnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DnsData       []byte                 `protobuf:"bytes,1,opt,name=dns_data,json=dnsData,proto3" json:"dns_data,omitempty"` // DNS 响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsResponse) Reset() {
	*x = DnsResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsResponse) ProtoMessage() {}

func (x *DnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsResponse.ProtoReflect.Descriptor instead.
func (*DnsResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{4}
}

func (x *DnsResponse) GetDnsData() []byte {
	if x != nil {
		return x.DnsData
	}
	return nil
}

// GetDnsRequest 获取 CDN DNS 信息请求
type GetDnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDnsRequest) Reset() {
	*x = GetDnsRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDnsRequest) ProtoMessage() {}

func (x *GetDnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDnsRequest.ProtoReflect.Descriptor instead.
func (*GetDnsRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{5}
}

// GetDnsResponse 获取 CDN DNS 信息响应
type GetDnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *DnsResponse           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // DNS 响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDnsResponse) Reset() {
	*x = GetDnsResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDnsResponse) ProtoMessage() {}

func (x *GetDnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDnsResponse.ProtoReflect.Descriptor instead.
func (*GetDnsResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{6}
}

func (x *GetDnsResponse) GetResult() *DnsResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

// UploadImageChunk 上传图片分块
type UploadImageChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*UploadImageChunk_Metadata
	//	*UploadImageChunk_Data
	Chunk         isUploadImageChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageChunk) Reset() {
	*x = UploadImageChunk{}
	mi := &file_cdn_cdn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageChunk) ProtoMessage() {}

func (x *UploadImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageChunk.ProtoReflect.Descriptor instead.
func (*UploadImageChunk) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{7}
}

func (x *UploadImageChunk) GetChunk() isUploadImageChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *UploadImageChunk) GetMetadata() *UploadImageMetadata {
	if x != nil {
		if x, ok := x.Chunk.(*UploadImageChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadImageChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*UploadImageChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadImageChunk_Chunk interface {
	isUploadImageChunk_Chunk()
}

type UploadImageChunk_Metadata struct {
	Metadata *UploadImageMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // 第一个包携带元数据
}

type UploadImageChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // 后续包携带数据
}

func (*UploadImageChunk_Metadata) isUploadImageChunk_Chunk() {}

func (*UploadImageChunk_Data) isUploadImageChunk_Chunk() {}

// UploadImageMetadata 上传图片元数据
type UploadImageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                     // 接收者 wxid
	TotalSize     uint32                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // 文件总大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageMetadata) Reset() {
	*x = UploadImageMetadata{}
	mi := &file_cdn_cdn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageMetadata) ProtoMessage() {}

func (x *UploadImageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageMetadata.ProtoReflect.Descriptor instead.
func (*UploadImageMetadata) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{8}
}

func (x *UploadImageMetadata) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UploadImageMetadata) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UploadVideoChunk 上传视频分块
type UploadVideoChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*UploadVideoChunk_Metadata
	//	*UploadVideoChunk_Data
	Chunk         isUploadVideoChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoChunk) Reset() {
	*x = UploadVideoChunk{}
	mi := &file_cdn_cdn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoChunk) ProtoMessage() {}

func (x *UploadVideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoChunk.ProtoReflect.Descriptor instead.
func (*UploadVideoChunk) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{9}
}

func (x *UploadVideoChunk) GetChunk() isUploadVideoChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *UploadVideoChunk) GetMetadata() *UploadVideoMetadata {
	if x != nil {
		if x, ok := x.Chunk.(*UploadVideoChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadVideoChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*UploadVideoChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadVideoChunk_Chunk interface {
	isUploadVideoChunk_Chunk()
}

type UploadVideoChunk_Metadata struct {
	Metadata *UploadVideoMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // 第一个包携带元数据
}

type UploadVideoChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // 后续包携带数据
}

func (*UploadVideoChunk_Metadata) isUploadVideoChunk_Chunk() {}

func (*UploadVideoChunk_Data) isUploadVideoChunk_Chunk() {}

// UploadVideoMetadata 上传视频元数据
type UploadVideoMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Receiver       string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                                      // 接收者 wxid
	VideoTotalSize uint32                 `protobuf:"varint,2,opt,name=video_total_size,json=videoTotalSize,proto3" json:"video_total_size,omitempty"` // 视频文件总大小
	ThumbTotalSize uint32                 `protobuf:"varint,3,opt,name=thumb_total_size,json=thumbTotalSize,proto3" json:"thumb_total_size,omitempty"` // 缩略图总大小
	Duration       uint32                 `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`                                     // 视频时长（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadVideoMetadata) Reset() {
	*x = UploadVideoMetadata{}
	mi := &file_cdn_cdn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoMetadata) ProtoMessage() {}

func (x *UploadVideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoMetadata.ProtoReflect.Descriptor instead.
func (*UploadVideoMetadata) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{10}
}

func (x *UploadVideoMetadata) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UploadVideoMetadata) GetVideoTotalSize() uint32 {
	if x != nil {
		return x.VideoTotalSize
	}
	return 0
}

func (x *UploadVideoMetadata) GetThumbTotalSize() uint32 {
	if x != nil {
		return x.ThumbTotalSize
	}
	return 0
}

func (x *UploadVideoMetadata) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// DownloadImageChunk 下载图片分块
type DownloadImageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 图片数据块
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageChunk) Reset() {
	*x = DownloadImageChunk{}
	mi := &file_cdn_cdn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageChunk) ProtoMessage() {}

func (x *DownloadImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageChunk.ProtoReflect.Descriptor instead.
func (*DownloadImageChunk) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVideoChunk 下载视频分块
type DownloadVideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 视频数据块
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoChunk) Reset() {
	*x = DownloadVideoChunk{}
	mi := &file_cdn_cdn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoChunk) ProtoMessage() {}

func (x *DownloadVideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoChunk.ProtoReflect.Descriptor instead.
func (*DownloadVideoChunk) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadVideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadImageResponse 上传图片响应
type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *UploadImageResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{13}
}

func (x *UploadImageResponse) GetResult() *UploadImageResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// UploadMomentsImageResponse 上传朋友圈图片响应
type UploadMomentsImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *UploadSnsImageResult  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMomentsImageResponse) Reset() {
	*x = UploadMomentsImageResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMomentsImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMomentsImageResponse) ProtoMessage() {}

func (x *UploadMomentsImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMomentsImageResponse.ProtoReflect.Descriptor instead.
func (*UploadMomentsImageResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{14}
}

func (x *UploadMomentsImageResponse) GetResult() *UploadSnsImageResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// UploadVideoResponse 上传视频响应
type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *UploadVideoResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{15}
}

func (x *UploadVideoResponse) GetResult() *UploadVideoResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// UploadMomentsVideoResponse 上传朋友圈视频响应
type UploadMomentsVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *UploadSnsVideoResult  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMomentsVideoResponse) Reset() {
	*x = UploadMomentsVideoResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMomentsVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMomentsVideoResponse) ProtoMessage() {}

func (x *UploadMomentsVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMomentsVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadMomentsVideoResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{16}
}

func (x *UploadMomentsVideoResponse) GetResult() *UploadSnsVideoResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// DownloadImageResponse 下载图片响应（非流式）
type DownloadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageResponse) Reset() {
	*x = DownloadImageResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageResponse) ProtoMessage() {}

func (x *DownloadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageResponse.ProtoReflect.Descriptor instead.
func (*DownloadImageResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVideoCoverResponse 下载视频封面响应
type DownloadVideoCoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoCoverResponse) Reset() {
	*x = DownloadVideoCoverResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoCoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoCoverResponse) ProtoMessage() {}

func (x *DownloadVideoCoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoCoverResponse.ProtoReflect.Descriptor instead.
func (*DownloadVideoCoverResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadVideoCoverResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadVideoResponse 下载视频响应（非流式）
type DownloadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoResponse) Reset() {
	*x = DownloadVideoResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoResponse) ProtoMessage() {}

func (x *DownloadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoResponse.ProtoReflect.Descriptor instead.
func (*DownloadVideoResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadVideoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DownloadSnsVideoResponse 下载朋友圈视频响应
type DownloadSnsVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSnsVideoResponse) Reset() {
	*x = DownloadSnsVideoResponse{}
	mi := &file_cdn_cdn_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSnsVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSnsVideoResponse) ProtoMessage() {}

func (x *DownloadSnsVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSnsVideoResponse.ProtoReflect.Descriptor instead.
func (*DownloadSnsVideoResponse) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{20}
}

func (x *DownloadSnsVideoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadImageRequest CDN 上传聊天图片请求（非流式，保留兼容）
type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者 wxid
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // 图片二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{21}
}

func (x *UploadImageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UploadImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadMomentsImageRequest CDN 上传朋友圈图片请求
type UploadMomentsImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 图片二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMomentsImageRequest) Reset() {
	*x = UploadMomentsImageRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMomentsImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMomentsImageRequest) ProtoMessage() {}

func (x *UploadMomentsImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMomentsImageRequest.ProtoReflect.Descriptor instead.
func (*UploadMomentsImageRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{22}
}

func (x *UploadMomentsImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadVideoRequest CDN 上传聊天视频请求（非流式，保留兼容）
type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                    // 接收者 wxid
	VideoData     []byte                 `protobuf:"bytes,2,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"` // 视频二进制数据
	ThumbData     []byte                 `protobuf:"bytes,3,opt,name=thumb_data,json=thumbData,proto3" json:"thumb_data,omitempty"` // 缩略图二进制数据
	Duration      uint32                 `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`                   // 视频时长（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{23}
}

func (x *UploadVideoRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UploadVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UploadVideoRequest) GetThumbData() []byte {
	if x != nil {
		return x.ThumbData
	}
	return nil
}

func (x *UploadVideoRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// UploadMomentsVideoRequest CDN 上传朋友圈视频请求
type UploadMomentsVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoData     []byte                 `protobuf:"bytes,1,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"` // 视频二进制数据
	ThumbData     []byte                 `protobuf:"bytes,2,opt,name=thumb_data,json=thumbData,proto3" json:"thumb_data,omitempty"` // 缩略图二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMomentsVideoRequest) Reset() {
	*x = UploadMomentsVideoRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMomentsVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMomentsVideoRequest) ProtoMessage() {}

func (x *UploadMomentsVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMomentsVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadMomentsVideoRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{24}
}

func (x *UploadMomentsVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UploadMomentsVideoRequest) GetThumbData() []byte {
	if x != nil {
		return x.ThumbData
	}
	return nil
}

// DownloadImageRequest CDN 下载高清图片请求
type DownloadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // CDN 文件ID
	AesKey        string                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // AES 密钥（hex编码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageRequest) Reset() {
	*x = DownloadImageRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageRequest) ProtoMessage() {}

func (x *DownloadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageRequest.ProtoReflect.Descriptor instead.
func (*DownloadImageRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{25}
}

func (x *DownloadImageRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadImageRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

// DownloadVideoCoverRequest CDN 下载视频封面请求
type DownloadVideoCoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // CDN 文件ID
	AesKey        string                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // AES 密钥（hex编码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoCoverRequest) Reset() {
	*x = DownloadVideoCoverRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoCoverRequest) ProtoMessage() {}

func (x *DownloadVideoCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoCoverRequest.ProtoReflect.Descriptor instead.
func (*DownloadVideoCoverRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{26}
}

func (x *DownloadVideoCoverRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadVideoCoverRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

// DownloadVideoRequest CDN 下载聊天视频请求
type DownloadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // CDN 文件ID
	AesKey        string                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // AES 密钥（hex编码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoRequest) Reset() {
	*x = DownloadVideoRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoRequest) ProtoMessage() {}

func (x *DownloadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoRequest.ProtoReflect.Descriptor instead.
func (*DownloadVideoRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{27}
}

func (x *DownloadVideoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadVideoRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

// DownloadSnsVideoRequest CDN 下载朋友圈视频请求
type DownloadSnsVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"` // 加密视频 URL
	EncKey        uint64                 `protobuf:"varint,2,opt,name=enc_key,json=encKey,proto3" json:"enc_key,omitempty"`      // 解密密钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSnsVideoRequest) Reset() {
	*x = DownloadSnsVideoRequest{}
	mi := &file_cdn_cdn_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSnsVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSnsVideoRequest) ProtoMessage() {}

func (x *DownloadSnsVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_cdn_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSnsVideoRequest.ProtoReflect.Descriptor instead.
func (*DownloadSnsVideoRequest) Descriptor() ([]byte, []int) {
	return file_cdn_cdn_proto_rawDescGZIP(), []int{28}
}

func (x *DownloadSnsVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *DownloadSnsVideoRequest) GetEncKey() uint64 {
	if x != nil {
		return x.EncKey
	}
	return 0
}

var File_cdn_cdn_proto protoreflect.FileDescriptor

const file_cdn_cdn_proto_rawDesc = "" +
	"\n" +
	"\rcdn/cdn.proto\x12\x03cdn\"\xfc\x02\n" +
	"\x11UploadImageResult\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x03 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\rR\n" +
	"createTime\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\rR\bfileSize\x12\x19\n" +
	"\bfile_md5\x18\x06 \x01(\tR\afileMd5\x12\x1d\n" +
	"\n" +
	"file_width\x18\a \x01(\rR\tfileWidth\x12\x1f\n" +
	"\vfile_height\x18\b \x01(\rR\n" +
	"fileHeight\x12\x1d\n" +
	"\n" +
	"thumb_size\x18\t \x01(\rR\tthumbSize\x12\x1b\n" +
	"\tthumb_md5\x18\n" +
	" \x01(\tR\bthumbMd5\x12\x1f\n" +
	"\vthumb_width\x18\v \x01(\rR\n" +
	"thumbWidth\x12!\n" +
	"\fthumb_height\x18\f \x01(\rR\vthumbHeight\"\xc8\x01\n" +
	"\x14UploadSnsImageResult\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tthumb_url\x18\x02 \x01(\tR\bthumbUrl\x12\x19\n" +
	"\bfile_key\x18\x03 \x01(\tR\afileKey\x12\x19\n" +
	"\bfile_md5\x18\x04 \x01(\tR\afileMd5\x12\x1f\n" +
	"\vimage_width\x18\x05 \x01(\rR\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\x06 \x01(\rR\vimageHeight\"\x9c\x01\n" +
	"\x11UploadVideoResult\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\rR\bfileSize\x12\x1d\n" +
	"\n" +
	"thumb_size\x18\x04 \x01(\rR\tthumbSize\x12\x19\n" +
	"\bfile_md5\x18\x05 \x01(\tR\afileMd5\"\x82\x01\n" +
	"\x14UploadSnsVideoResult\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tthumb_url\x18\x02 \x01(\tR\bthumbUrl\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x19\n" +
	"\bfile_key\x18\x04 \x01(\tR\afileKey\"(\n" +
	"\vDnsResponse\x12\x19\n" +
	"\bdns_data\x18\x01 \x01(\fR\adnsData\"\x0f\n" +
	"\rGetDnsRequest\":\n" +
	"\x0eGetDnsResponse\x12(\n" +
	"\x06result\x18\x01 \x01(\v2\x10.cdn.DnsResponseR\x06result\"i\n" +
	"\x10UploadImageChunk\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.cdn.UploadImageMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05chunk\"P\n" +
	"\x13UploadImageMetadata\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\rR\ttotalSize\"i\n" +
	"\x10UploadVideoChunk\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.cdn.UploadVideoMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05chunk\"\xa1\x01\n" +
	"\x13UploadVideoMetadata\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12(\n" +
	"\x10video_total_size\x18\x02 \x01(\rR\x0evideoTotalSize\x12(\n" +
	"\x10thumb_total_size\x18\x03 \x01(\rR\x0ethumbTotalSize\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\rR\bduration\"(\n" +
	"\x12DownloadImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"(\n" +
	"\x12DownloadVideoChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"E\n" +
	"\x13UploadImageResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.cdn.UploadImageResultR\x06result\"O\n" +
	"\x1aUploadMomentsImageResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.cdn.UploadSnsImageResultR\x06result\"E\n" +
	"\x13UploadVideoResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.cdn.UploadVideoResultR\x06result\"O\n" +
	"\x1aUploadMomentsVideoResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.cdn.UploadSnsVideoResultR\x06result\"+\n" +
	"\x15DownloadImageResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"0\n" +
	"\x1aDownloadVideoCoverResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"+\n" +
	"\x15DownloadVideoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\".\n" +
	"\x18DownloadSnsVideoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"D\n" +
	"\x12UploadImageRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"/\n" +
	"\x19UploadMomentsImageRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8a\x01\n" +
	"\x12UploadVideoRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x1d\n" +
	"\n" +
	"video_data\x18\x02 \x01(\fR\tvideoData\x12\x1d\n" +
	"\n" +
	"thumb_data\x18\x03 \x01(\fR\tthumbData\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\rR\bduration\"Y\n" +
	"\x19UploadMomentsVideoRequest\x12\x1d\n" +
	"\n" +
	"video_data\x18\x01 \x01(\fR\tvideoData\x12\x1d\n" +
	"\n" +
	"thumb_data\x18\x02 \x01(\fR\tthumbData\"H\n" +
	"\x14DownloadImageRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\tR\x06aesKey\"M\n" +
	"\x19DownloadVideoCoverRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\tR\x06aesKey\"H\n" +
	"\x14DownloadVideoRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\tR\x06aesKey\"O\n" +
	"\x17DownloadSnsVideoRequest\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12\x17\n" +
	"\aenc_key\x18\x02 \x01(\x04R\x06encKey*\x9b\x01\n" +
	"\fDownloadType\x12\x1d\n" +
	"\x19DOWNLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DOWNLOAD_TYPE_IMAGE\x10\x01\x12\x17\n" +
	"\x13DOWNLOAD_TYPE_VIDEO\x10\x02\x12\x1d\n" +
	"\x19DOWNLOAD_TYPE_VIDEO_COVER\x10\x03\x12\x1b\n" +
	"\x17DOWNLOAD_TYPE_SNS_VIDEO\x10\x042\xa7\x05\n" +
	"\n" +
	"CDNService\x121\n" +
	"\x06GetDns\x12\x12.cdn.GetDnsRequest\x1a\x13.cdn.GetDnsResponse\x12@\n" +
	"\vUploadImage\x12\x15.cdn.UploadImageChunk\x1a\x18.cdn.UploadImageResponse(\x01\x12@\n" +
	"\vUploadVideo\x12\x15.cdn.UploadVideoChunk\x1a\x18.cdn.UploadVideoResponse(\x01\x12E\n" +
	"\rDownloadImage\x12\x19.cdn.DownloadImageRequest\x1a\x17.cdn.DownloadImageChunk0\x01\x12E\n" +
	"\rDownloadVideo\x12\x19.cdn.DownloadVideoRequest\x1a\x17.cdn.DownloadVideoChunk0\x01\x12U\n" +
	"\x12UploadMomentsImage\x12\x1e.cdn.UploadMomentsImageRequest\x1a\x1f.cdn.UploadMomentsImageResponse\x12U\n" +
	"\x12UploadMomentsVideo\x12\x1e.cdn.UploadMomentsVideoRequest\x1a\x1f.cdn.UploadMomentsVideoResponse\x12U\n" +
	"\x12DownloadVideoCover\x12\x1e.cdn.DownloadVideoCoverRequest\x1a\x1f.cdn.DownloadVideoCoverResponse\x12O\n" +
	"\x10DownloadSnsVideo\x12\x1c.cdn.DownloadSnsVideoRequest\x1a\x1d.cdn.DownloadSnsVideoResponseBb\n" +
	"\acom.cdnB\bCdnProtoP\x01Z!github.com/sbgayhub/golem/sdk/cdn\xa2\x02\x03CXX\xaa\x02\x03Cdn\xca\x02\x03Cdn\xe2\x02\x0fCdn\\GPBMetadata\xea\x02\x03Cdnb\x06proto3"

var (
	file_cdn_cdn_proto_rawDescOnce sync.Once
	file_cdn_cdn_proto_rawDescData []byte
)

func file_cdn_cdn_proto_rawDescGZIP() []byte {
	file_cdn_cdn_proto_rawDescOnce.Do(func() {
		file_cdn_cdn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdn_cdn_proto_rawDesc), len(file_cdn_cdn_proto_rawDesc)))
	})
	return file_cdn_cdn_proto_rawDescData
}

var file_cdn_cdn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cdn_cdn_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_cdn_cdn_proto_goTypes = []any{
	(DownloadType)(0),                  // 0: cdn.DownloadType
	(*UploadImageResult)(nil),          // 1: cdn.UploadImageResult
	(*UploadSnsImageResult)(nil),       // 2: cdn.UploadSnsImageResult
	(*UploadVideoResult)(nil),          // 3: cdn.UploadVideoResult
	(*UploadSnsVideoResult)(nil),       // 4: cdn.UploadSnsVideoResult
	(*DnsResponse)(nil),                // 5: cdn.DnsResponse
	(*GetDnsRequest)(nil),              // 6: cdn.GetDnsRequest
	(*GetDnsResponse)(nil),             // 7: cdn.GetDnsResponse
	(*UploadImageChunk)(nil),           // 8: cdn.UploadImageChunk
	(*UploadImageMetadata)(nil),        // 9: cdn.UploadImageMetadata
	(*UploadVideoChunk)(nil),           // 10: cdn.UploadVideoChunk
	(*UploadVideoMetadata)(nil),        // 11: cdn.UploadVideoMetadata
	(*DownloadImageChunk)(nil),         // 12: cdn.DownloadImageChunk
	(*DownloadVideoChunk)(nil),         // 13: cdn.DownloadVideoChunk
	(*UploadImageResponse)(nil),        // 14: cdn.UploadImageResponse
	(*UploadMomentsImageResponse)(nil), // 15: cdn.UploadMomentsImageResponse
	(*UploadVideoResponse)(nil),        // 16: cdn.UploadVideoResponse
	(*UploadMomentsVideoResponse)(nil), // 17: cdn.UploadMomentsVideoResponse
	(*DownloadImageResponse)(nil),      // 18: cdn.DownloadImageResponse
	(*DownloadVideoCoverResponse)(nil), // 19: cdn.DownloadVideoCoverResponse
	(*DownloadVideoResponse)(nil),      // 20: cdn.DownloadVideoResponse
	(*DownloadSnsVideoResponse)(nil),   // 21: cdn.DownloadSnsVideoResponse
	(*UploadImageRequest)(nil),         // 22: cdn.UploadImageRequest
	(*UploadMomentsImageRequest)(nil),  // 23: cdn.UploadMomentsImageRequest
	(*UploadVideoRequest)(nil),         // 24: cdn.UploadVideoRequest
	(*UploadMomentsVideoRequest)(nil),  // 25: cdn.UploadMomentsVideoRequest
	(*DownloadImageRequest)(nil),       // 26: cdn.DownloadImageRequest
	(*DownloadVideoCoverRequest)(nil),  // 27: cdn.DownloadVideoCoverRequest
	(*DownloadVideoRequest)(nil),       // 28: cdn.DownloadVideoRequest
	(*DownloadSnsVideoRequest)(nil),    // 29: cdn.DownloadSnsVideoRequest
}
var file_cdn_cdn_proto_depIdxs = []int32{
	5,  // 0: cdn.GetDnsResponse.result:type_name -> cdn.DnsResponse
	9,  // 1: cdn.UploadImageChunk.metadata:type_name -> cdn.UploadImageMetadata
	11, // 2: cdn.UploadVideoChunk.metadata:type_name -> cdn.UploadVideoMetadata
	1,  // 3: cdn.UploadImageResponse.result:type_name -> cdn.UploadImageResult
	2,  // 4: cdn.UploadMomentsImageResponse.result:type_name -> cdn.UploadSnsImageResult
	3,  // 5: cdn.UploadVideoResponse.result:type_name -> cdn.UploadVideoResult
	4,  // 6: cdn.UploadMomentsVideoResponse.result:type_name -> cdn.UploadSnsVideoResult
	6,  // 7: cdn.CDNService.GetDns:input_type -> cdn.GetDnsRequest
	8,  // 8: cdn.CDNService.UploadImage:input_type -> cdn.UploadImageChunk
	10, // 9: cdn.CDNService.UploadVideo:input_type -> cdn.UploadVideoChunk
	26, // 10: cdn.CDNService.DownloadImage:input_type -> cdn.DownloadImageRequest
	28, // 11: cdn.CDNService.DownloadVideo:input_type -> cdn.DownloadVideoRequest
	23, // 12: cdn.CDNService.UploadMomentsImage:input_type -> cdn.UploadMomentsImageRequest
	25, // 13: cdn.CDNService.UploadMomentsVideo:input_type -> cdn.UploadMomentsVideoRequest
	27, // 14: cdn.CDNService.DownloadVideoCover:input_type -> cdn.DownloadVideoCoverRequest
	29, // 15: cdn.CDNService.DownloadSnsVideo:input_type -> cdn.DownloadSnsVideoRequest
	7,  // 16: cdn.CDNService.GetDns:output_type -> cdn.GetDnsResponse
	14, // 17: cdn.CDNService.UploadImage:output_type -> cdn.UploadImageResponse
	16, // 18: cdn.CDNService.UploadVideo:output_type -> cdn.UploadVideoResponse
	12, // 19: cdn.CDNService.DownloadImage:output_type -> cdn.DownloadImageChunk
	13, // 20: cdn.CDNService.DownloadVideo:output_type -> cdn.DownloadVideoChunk
	15, // 21: cdn.CDNService.UploadMomentsImage:output_type -> cdn.UploadMomentsImageResponse
	17, // 22: cdn.CDNService.UploadMomentsVideo:output_type -> cdn.UploadMomentsVideoResponse
	19, // 23: cdn.CDNService.DownloadVideoCover:output_type -> cdn.DownloadVideoCoverResponse
	21, // 24: cdn.CDNService.DownloadSnsVideo:output_type -> cdn.DownloadSnsVideoResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cdn_cdn_proto_init() }
func file_cdn_cdn_proto_init() {
	if File_cdn_cdn_proto != nil {
		return
	}
	file_cdn_cdn_proto_msgTypes[7].OneofWrappers = []any{
		(*UploadImageChunk_Metadata)(nil),
		(*UploadImageChunk_Data)(nil),
	}
	file_cdn_cdn_proto_msgTypes[9].OneofWrappers = []any{
		(*UploadVideoChunk_Metadata)(nil),
		(*UploadVideoChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdn_cdn_proto_rawDesc), len(file_cdn_cdn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdn_cdn_proto_goTypes,
		DependencyIndexes: file_cdn_cdn_proto_depIdxs,
		EnumInfos:         file_cdn_cdn_proto_enumTypes,
		MessageInfos:      file_cdn_cdn_proto_msgTypes,
	}.Build()
	File_cdn_cdn_proto = out.File
	file_cdn_cdn_proto_goTypes = nil
	file_cdn_cdn_proto_depIdxs = nil
}
