// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cdn/cdn.proto

package cdn

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CDNService_UploadImage_FullMethodName        = "/cdn.CDNService/UploadImage"
	CDNService_UploadVideo_FullMethodName        = "/cdn.CDNService/UploadVideo"
	CDNService_DownloadImage_FullMethodName      = "/cdn.CDNService/DownloadImage"
	CDNService_DownloadVideo_FullMethodName      = "/cdn.CDNService/DownloadVideo"
	CDNService_UploadMomentsImage_FullMethodName = "/cdn.CDNService/UploadMomentsImage"
	CDNService_UploadMomentsVideo_FullMethodName = "/cdn.CDNService/UploadMomentsVideo"
	CDNService_DownloadVideoCover_FullMethodName = "/cdn.CDNService/DownloadVideoCover"
	CDNService_DownloadSnsVideo_FullMethodName   = "/cdn.CDNService/DownloadSnsVideo"
)

// CDNServiceClient is the client API for CDNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CDNService CDN 文件上传/下载服务
type CDNServiceClient interface {
	// 客户端流式上传聊天图片
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadImageChunk, UploadImageResponse], error)
	// 客户端流式上传聊天视频
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadVideoChunk, UploadVideoResponse], error)
	// 服务端流式下载高清图片
	DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadImageChunk], error)
	// 服务端流式下载聊天视频
	DownloadVideo(ctx context.Context, in *DownloadVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadVideoChunk], error)
	// 非流式接口（小文件）
	// CDN 上传朋友圈图片
	UploadMomentsImage(ctx context.Context, in *UploadMomentsImageRequest, opts ...grpc.CallOption) (*UploadMomentsImageResponse, error)
	// CDN 上传朋友圈视频
	UploadMomentsVideo(ctx context.Context, in *UploadMomentsVideoRequest, opts ...grpc.CallOption) (*UploadMomentsVideoResponse, error)
	// CDN 下载视频封面
	DownloadVideoCover(ctx context.Context, in *DownloadVideoCoverRequest, opts ...grpc.CallOption) (*DownloadVideoCoverResponse, error)
	// CDN 下载朋友圈视频
	DownloadSnsVideo(ctx context.Context, in *DownloadSnsVideoRequest, opts ...grpc.CallOption) (*DownloadMomentsVideoResponse, error)
}

type cDNServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCDNServiceClient(cc grpc.ClientConnInterface) CDNServiceClient {
	return &cDNServiceClient{cc}
}

func (c *cDNServiceClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadImageChunk, UploadImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CDNService_ServiceDesc.Streams[0], CDNService_UploadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadImageChunk, UploadImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_UploadImageClient = grpc.ClientStreamingClient[UploadImageChunk, UploadImageResponse]

func (c *cDNServiceClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadVideoChunk, UploadVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CDNService_ServiceDesc.Streams[1], CDNService_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadVideoChunk, UploadVideoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_UploadVideoClient = grpc.ClientStreamingClient[UploadVideoChunk, UploadVideoResponse]

func (c *cDNServiceClient) DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadImageChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CDNService_ServiceDesc.Streams[2], CDNService_DownloadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadImageRequest, DownloadImageChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_DownloadImageClient = grpc.ServerStreamingClient[DownloadImageChunk]

func (c *cDNServiceClient) DownloadVideo(ctx context.Context, in *DownloadVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadVideoChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CDNService_ServiceDesc.Streams[3], CDNService_DownloadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadVideoRequest, DownloadVideoChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_DownloadVideoClient = grpc.ServerStreamingClient[DownloadVideoChunk]

func (c *cDNServiceClient) UploadMomentsImage(ctx context.Context, in *UploadMomentsImageRequest, opts ...grpc.CallOption) (*UploadMomentsImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadMomentsImageResponse)
	err := c.cc.Invoke(ctx, CDNService_UploadMomentsImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDNServiceClient) UploadMomentsVideo(ctx context.Context, in *UploadMomentsVideoRequest, opts ...grpc.CallOption) (*UploadMomentsVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadMomentsVideoResponse)
	err := c.cc.Invoke(ctx, CDNService_UploadMomentsVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDNServiceClient) DownloadVideoCover(ctx context.Context, in *DownloadVideoCoverRequest, opts ...grpc.CallOption) (*DownloadVideoCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadVideoCoverResponse)
	err := c.cc.Invoke(ctx, CDNService_DownloadVideoCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDNServiceClient) DownloadSnsVideo(ctx context.Context, in *DownloadSnsVideoRequest, opts ...grpc.CallOption) (*DownloadMomentsVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadMomentsVideoResponse)
	err := c.cc.Invoke(ctx, CDNService_DownloadSnsVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDNServiceServer is the server API for CDNService service.
// All implementations must embed UnimplementedCDNServiceServer
// for forward compatibility.
//
// CDNService CDN 文件上传/下载服务
type CDNServiceServer interface {
	// 客户端流式上传聊天图片
	UploadImage(grpc.ClientStreamingServer[UploadImageChunk, UploadImageResponse]) error
	// 客户端流式上传聊天视频
	UploadVideo(grpc.ClientStreamingServer[UploadVideoChunk, UploadVideoResponse]) error
	// 服务端流式下载高清图片
	DownloadImage(*DownloadImageRequest, grpc.ServerStreamingServer[DownloadImageChunk]) error
	// 服务端流式下载聊天视频
	DownloadVideo(*DownloadVideoRequest, grpc.ServerStreamingServer[DownloadVideoChunk]) error
	// 非流式接口（小文件）
	// CDN 上传朋友圈图片
	UploadMomentsImage(context.Context, *UploadMomentsImageRequest) (*UploadMomentsImageResponse, error)
	// CDN 上传朋友圈视频
	UploadMomentsVideo(context.Context, *UploadMomentsVideoRequest) (*UploadMomentsVideoResponse, error)
	// CDN 下载视频封面
	DownloadVideoCover(context.Context, *DownloadVideoCoverRequest) (*DownloadVideoCoverResponse, error)
	// CDN 下载朋友圈视频
	DownloadSnsVideo(context.Context, *DownloadSnsVideoRequest) (*DownloadMomentsVideoResponse, error)
	mustEmbedUnimplementedCDNServiceServer()
}

// UnimplementedCDNServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCDNServiceServer struct{}

func (UnimplementedCDNServiceServer) UploadImage(grpc.ClientStreamingServer[UploadImageChunk, UploadImageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedCDNServiceServer) UploadVideo(grpc.ClientStreamingServer[UploadVideoChunk, UploadVideoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedCDNServiceServer) DownloadImage(*DownloadImageRequest, grpc.ServerStreamingServer[DownloadImageChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadImage not implemented")
}
func (UnimplementedCDNServiceServer) DownloadVideo(*DownloadVideoRequest, grpc.ServerStreamingServer[DownloadVideoChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadVideo not implemented")
}
func (UnimplementedCDNServiceServer) UploadMomentsImage(context.Context, *UploadMomentsImageRequest) (*UploadMomentsImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadMomentsImage not implemented")
}
func (UnimplementedCDNServiceServer) UploadMomentsVideo(context.Context, *UploadMomentsVideoRequest) (*UploadMomentsVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadMomentsVideo not implemented")
}
func (UnimplementedCDNServiceServer) DownloadVideoCover(context.Context, *DownloadVideoCoverRequest) (*DownloadVideoCoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadVideoCover not implemented")
}
func (UnimplementedCDNServiceServer) DownloadSnsVideo(context.Context, *DownloadSnsVideoRequest) (*DownloadMomentsVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadSnsVideo not implemented")
}
func (UnimplementedCDNServiceServer) mustEmbedUnimplementedCDNServiceServer() {}
func (UnimplementedCDNServiceServer) testEmbeddedByValue()                    {}

// UnsafeCDNServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CDNServiceServer will
// result in compilation errors.
type UnsafeCDNServiceServer interface {
	mustEmbedUnimplementedCDNServiceServer()
}

func RegisterCDNServiceServer(s grpc.ServiceRegistrar, srv CDNServiceServer) {
	// If the following call pancis, it indicates UnimplementedCDNServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CDNService_ServiceDesc, srv)
}

func _CDNService_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CDNServiceServer).UploadImage(&grpc.GenericServerStream[UploadImageChunk, UploadImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_UploadImageServer = grpc.ClientStreamingServer[UploadImageChunk, UploadImageResponse]

func _CDNService_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CDNServiceServer).UploadVideo(&grpc.GenericServerStream[UploadVideoChunk, UploadVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_UploadVideoServer = grpc.ClientStreamingServer[UploadVideoChunk, UploadVideoResponse]

func _CDNService_DownloadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CDNServiceServer).DownloadImage(m, &grpc.GenericServerStream[DownloadImageRequest, DownloadImageChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_DownloadImageServer = grpc.ServerStreamingServer[DownloadImageChunk]

func _CDNService_DownloadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadVideoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CDNServiceServer).DownloadVideo(m, &grpc.GenericServerStream[DownloadVideoRequest, DownloadVideoChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CDNService_DownloadVideoServer = grpc.ServerStreamingServer[DownloadVideoChunk]

func _CDNService_UploadMomentsImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadMomentsImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDNServiceServer).UploadMomentsImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDNService_UploadMomentsImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDNServiceServer).UploadMomentsImage(ctx, req.(*UploadMomentsImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDNService_UploadMomentsVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadMomentsVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDNServiceServer).UploadMomentsVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDNService_UploadMomentsVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDNServiceServer).UploadMomentsVideo(ctx, req.(*UploadMomentsVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDNService_DownloadVideoCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadVideoCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDNServiceServer).DownloadVideoCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDNService_DownloadVideoCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDNServiceServer).DownloadVideoCover(ctx, req.(*DownloadVideoCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDNService_DownloadSnsVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSnsVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDNServiceServer).DownloadSnsVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDNService_DownloadSnsVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDNServiceServer).DownloadSnsVideo(ctx, req.(*DownloadSnsVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CDNService_ServiceDesc is the grpc.ServiceDesc for CDNService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CDNService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdn.CDNService",
	HandlerType: (*CDNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadMomentsImage",
			Handler:    _CDNService_UploadMomentsImage_Handler,
		},
		{
			MethodName: "UploadMomentsVideo",
			Handler:    _CDNService_UploadMomentsVideo_Handler,
		},
		{
			MethodName: "DownloadVideoCover",
			Handler:    _CDNService_DownloadVideoCover_Handler,
		},
		{
			MethodName: "DownloadSnsVideo",
			Handler:    _CDNService_DownloadSnsVideo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImage",
			Handler:       _CDNService_UploadImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadVideo",
			Handler:       _CDNService_UploadVideo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadImage",
			Handler:       _CDNService_DownloadImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadVideo",
			Handler:       _CDNService_DownloadVideo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdn/cdn.proto",
}
